version: "3"
services:
  gym-backend:
    container_name: gym-backend
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:workdout@postgres:5432/workdout
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
  postgres:
    container_name: postgres
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: workdout
      POSTGRES_DB: workdout
volumes:
    db-data: